---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-test
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: rook-test
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  namespace: rook-test  
  labels:
    app: nginx
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: rook-test  
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.12-alpine
        name: nginx
        env:
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: nginx-pv-claim
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-egress
#   namespace: rook-test
# spec:
#   podSelector:
#     matchLabels:
#       app: nginx
#   egress: 
#   - {}
#   policyTypes:
#   - Egress
