apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: arp
      arp-network: 172.30.0.0/23
      cidr:
      # 172.30.1.96-12
      - 172.30.1.96/27
    # address-pools:
    # - name: default
    #   protocol: arp
    #   arp-network: 10.0.0.0/8
    #   cidr:
    #   - 10.42.42.0/24